name: Sequential Terraform Modules

on:
  push:
    paths:
      - 'terraform/**'
    branches:
      - main

jobs:
  network:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/1-network
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - run: terraform validate
      - run: terraform plan -out=tfplan
      - run: terraform apply -auto-approve tfplan

  storage:
    needs: network
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/2-storage
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - run: terraform validate
      - run: terraform plan -out=tfplan
      - run: terraform apply -auto-approve tfplan

  compute:
    needs: storage
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/3-compute
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - run: terraform validate
      - run: terraform plan -out=tfplan
      - run: terraform apply -auto-approve tfplan
