name: Terraform Deploy with Push Back

on:
  push:
    paths:
      - 'terraform/**'
      - 'tf-modules/**'
      - '.github/workflows/terraform.yml'
    branches:
      - main

  
  workflow_dispatch:

jobs:
  network:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Apply Network
        run: |
          terraform -chdir=terraform/network init
          terraform -chdir=terraform/network apply -auto-approve

  storage:
    runs-on: ubuntu-latest
    needs: network  
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Apply Storage
        run: |
          terraform -chdir=terraform/storage init
          terraform -chdir=terraform/storage apply -auto-approve

  compute:
    runs-on: ubuntu-latest
    needs: storage  
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Apply Compute
        run: |
          terraform -chdir=terraform/compute init
          terraform -chdir=terraform/compute apply -auto-approve
