name: Terraform Deploy with Push Back

on:
  push:
    paths:
      - 'terraform/**'
      - 'tf-modules/**'
      - '.github/workflows/terraform.yml'
    branches:
      - main

  
  workflow_dispatch:
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # --- Network module ---
      - name: Init Network
        run: terraform -chdir=tf-modules/network init

      - name: Apply Network
        run: terraform -chdir=tf-modules/network apply -auto-approve

      # --- Storage module (depends on Network) ---
      - name: Init Storage
        run: terraform -chdir=tf-modules/storage init

      - name: Apply Storage
        run: terraform -chdir=tf-modules/storage apply -auto-approve

      # --- Compute module (depends on Storage) ---
      - name: Init Compute
        run: terraform -chdir=tf-modules/compute init

      - name: Apply Compute
        run: terraform -chdir=tf-modules/compute apply -auto-approve
